# Copyright (c) 2020, NVIDIA CORPORATION.

# Usage:
#   conda build -c nvidia -c rapidsai -c conda-forge -c defaults .
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '9.2').split('.')[:2]) %}
{% set cuda_major = environ.get('CUDA', '9.2').split('.')[0] %}
{% set cuda_minor = environ.get('CUDA', '9.2').split('.')[1] %}

package:
  name: libclx
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CC
    - CXX
    - CUDAHOSTCXX
    - PARALLEL_LEVEL
    - VERSION_SUFFIX

requirements:
  build:
    - cmake>=3.14
    - libcudf={{ minor_version }}
    - cudatoolkit {{ cuda_version }}.*
  run:
    - libcudf={{ minor_version }}
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_file: ../../../LICENSE
  summary: libclx library
